ValueSet: VsEdqmPdfIntendedSite
Id: edqmPdfIntendedSite
Title: "EDQM PDF characteristics: Intended Site"
Description: "EDQM Pharmaceutical dose forms characteristics: Intended site"
* ^status = #draft
* ^experimental = true
* $standardterms#0021 "Auricular"
* $standardterms#0022 "Cutaneous/Transdermal"
* $standardterms#0023 "Dental"
* $standardterms#0024 "Environmental"
* $standardterms#0025 "Extracorporeal"
* $standardterms#0027 "Intrauterine"
* $standardterms#0028 "Intravesical/Urethral"
* $standardterms#0029 "Nasal"
* $standardterms#0030 "Ocular"
* $standardterms#0031 "Oral"
* $standardterms#0032 "Oromucosal"
* $standardterms#0033 "Parenteral"
* $standardterms#0034 "Pulmonary"
* $standardterms#0035 "Rectal"
* $standardterms#0036 "Vaginal"
* $standardterms#0037 "Unknown/Miscellaneous"
* $standardterms#0105 "Endocervical"
* $standardterms#0106 "Gastric"
* $standardterms#0107 "Gastroenteral"
* $standardterms#0108 "Intestinal"
* $standardterms#0109 "Intraperitoneal"